name: Compile CV latex

on: [push, pull_request, workflow_dispatch]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latex
      run: sudo apt-get install -yq texlive texlive-latex-extra texlive-lang-all
    - name: Install extra package
      run: sudo apt-get install -yq texlive-science
    
    - name: Compile CV English
      uses: ./.github/actions/compile
      with:
        document_tex: "cv.tex"
        location_file: "cv/latex/english"
        
    - name: Compile CV Francais
      uses: ./.github/actions/compile
      with:
        document_tex: "cv.tex"
        location_file: "cv/latex/francais"
          
    - name: Move final version
      run: |
        cp cv/latex/english/cv.pdf cv/cv_en.pdf
        cp cv/latex/francais/cv.pdf cv/cv_fr.pdf
        
    - name: Pull modif
      run: git pull
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Compile latex
        file_pattern: cv/latex/english/*.pdf cv/latex/francais/*.pdf cv/*.pdf
        push_options: '--force'
